services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      # Mount source code for live updates during development
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
    environment:
      - PYTHONUNBUFFERED=1
