version: '3'

vars:

tasks:
  test:
    desc: Run all tests (unit and integration)
    cmds:
      - uv run pytest

  test-unit:
    desc: Run unit tests only
    cmds:
      - uv run pytest -m unit

  test-integration:
    desc: Run integration tests
    cmds:
      - uv run pytest -m integration

  lint:
    desc: Run linting checks
    cmds:
      - uv run ruff check

  format:
    desc: Format code
    cmds:
      - uv run ruff format

  up:
    desc: Start WAHA service via docker-compose
    cmds:
      - docker-compose up -d waha

  down:
    desc: Stop WAHA service and reset database
    cmds:
      - docker-compose down
      - rm -f ./data/choresir.db

  dev:
    desc: Run FastAPI for local development
    dotenv: ['.env']
    cmds:
      - |
        echo "Development environment ready!"
        echo "  FastAPI    http://0.0.0.0:8001"
        echo "  WAHA       http://localhost:3000 (start with 'task up')"
        echo ""
        uv run uvicorn src.main:app --host 0.0.0.0 --port 8001

  stop-dev:
    desc: Stop all development services
    cmds:
      - |
        if [ -f .fastapi.pid ]; then
          kill $(cat .fastapi.pid) 2>/dev/null || true
          rm .fastapi.pid
          echo "FastAPI stopped"
        fi
        echo "All services stopped"

  down:
    desc: Tear down all development services and clean up
    cmds:
      - |
        echo "Stopping all services..."

        if [ -f .fastapi.pid ]; then
          kill $(cat .fastapi.pid) 2>/dev/null || true
          rm .fastapi.pid
          echo "✓ FastAPI stopped (via PID file)"
        fi

        FASTAPI_PID=$(lsof -ti :8001) || true
        if [ -n "$FASTAPI_PID" ]; then
          kill $FASTAPI_PID 2>/dev/null || true
          echo "✓ FastAPI stopped (port 8001)"
        fi

        if [ -f fastapi.log ]; then
          rm fastapi.log
          echo "✓ Removed fastapi.log"
        fi

        echo ""
        echo "All services stopped and cleaned up!"

  clean:
    desc: Clean up generated files
    cmds:
      - echo "No cleanup required"
