version: '3'

tasks:
  test:
    desc: Run all tests (unit and integration)
    cmds:
      - uv run pytest

  test-unit:
    desc: Run unit tests only
    cmds:
      - uv run pytest -m unit

  test-integration:
    desc: Run integration tests
    cmds:
      - uv run pytest -m integration

  lint:
    desc: Run linting checks
    cmds:
      - uv run ruff check

  format:
    desc: Format code
    cmds:
      - uv run ruff format

  dev:
    desc: Run FastAPI and ngrok concurrently for local development
    cmds:
      - |
        echo "Starting development environment..."

        # Start FastAPI in background
        echo "Starting FastAPI on http://0.0.0.0:8000..."
        NO_COLOR=1 uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &
        FASTAPI_PID=$!
        echo $FASTAPI_PID > .fastapi.pid

        # Wait for FastAPI to be ready
        echo "Waiting for FastAPI to be ready..."
        sleep 5

        # Check if FastAPI started successfully
        if ! curl -s http://localhost:8000/health > /dev/null 2>&1; then
          echo "ERROR: FastAPI failed to start. Check fastapi.log for details."
          echo "Shutting down services..."
          kill $FASTAPI_PID 2>/dev/null || true
          rm -f .fastapi.pid
          exit 1
        fi
        echo "FastAPI is ready!"

        # Start ngrok (foreground)
        echo "Starting ngrok..."

        # Check if we have a saved static domain
        if [ -f .ngrok-domain ] && [ -s .ngrok-domain ]; then
          SAVED_DOMAIN=$(cat .ngrok-domain)
          echo "Using saved static domain: $SAVED_DOMAIN"
          echo "Webhook URL: https://$SAVED_DOMAIN/webhook/whatsapp"
          ngrok http 8000 --domain=$SAVED_DOMAIN
        else
          echo "No static domain configured."
          echo "To use a static domain:"
          echo "  1. Visit https://dashboard.ngrok.com/domains"
          echo "  2. Create a new domain (free plan includes 1 static domain)"
          echo "  3. Save the domain to .ngrok-domain file"
          echo ""
          echo "Using random domain for now..."
          ngrok http 8000
        fi

        # Cleanup on exit
        echo "Shutting down services..."
        kill $FASTAPI_PID 2>/dev/null || true
        rm -f .fastapi.pid

  stop-dev:
    desc: Stop all development services
    cmds:
      - |
        if [ -f .fastapi.pid ]; then
          kill $(cat .fastapi.pid) 2>/dev/null || true
          rm .fastapi.pid
          echo "FastAPI stopped"
        fi
        pkill -f "ngrok http" 2>/dev/null || true
        echo "All services stopped"

  down:
    desc: Tear down all development services and clean up
    cmds:
      - |
        echo "Stopping all services..."

        # Stop services using PID files
        if [ -f .fastapi.pid ]; then
          kill $(cat .fastapi.pid) 2>/dev/null || true
          rm .fastapi.pid
          echo "✓ FastAPI stopped (via PID file)"
        fi

        # Kill any remaining processes by port
        FASTAPI_PID=$(lsof -ti :8000) || true
        if [ -n "$FASTAPI_PID" ]; then
          kill $FASTAPI_PID 2>/dev/null || true
          echo "✓ FastAPI stopped (port 8000)"
        fi

        # Kill ngrok
        pkill -f "ngrok http" 2>/dev/null && echo "✓ ngrok stopped" || true

        # Clean up log files
        if [ -f fastapi.log ]; then
          rm fastapi.log
          echo "✓ Removed fastapi.log"
        fi

        echo ""
        echo "All services stopped and cleaned up!"

  setup-ngrok:
    desc: Configure ngrok static domain
    cmds:
      - |
        echo "=== ngrok Static Domain Setup ==="
        echo ""
        echo "Free ngrok plan includes 1 static domain."
        echo ""
        echo "Steps:"
        echo "1. Visit https://dashboard.ngrok.com/domains"
        echo "2. Click 'Create Domain' (if you haven't already)"
        echo "3. Copy the domain name (e.g., 'abc-xyz-123.ngrok-free.app')"
        echo ""
        read -p "Enter your static domain: " STATIC_DOMAIN

        if [ -n "$STATIC_DOMAIN" ]; then
          echo "$STATIC_DOMAIN" > .ngrok-domain
          echo ""
          echo "✅ Static domain saved!"
          echo "Your webhook URL will be: https://$STATIC_DOMAIN/webhook/whatsapp"
          echo ""
          echo "Run 'task dev' to start with this domain."
        else
          echo "No domain entered. Skipping."
        fi

  deploy:
    desc: Deploy to Railway (requires Railway CLI)
    cmds:
      - |
        if ! command -v railway &> /dev/null; then
          echo "Railway CLI not found. Install with: npm install -g @railway/cli"
          exit 1
        fi
      - echo "Deploying to Railway..."
      - railway up

  deploy-status:
    desc: Check Railway deployment status
    cmds:
      - |
        if ! command -v railway &> /dev/null; then
          echo "Railway CLI not found. Install with: npm install -g @railway/cli"
          exit 1
        fi
      - railway status

  deploy-logs:
    desc: View Railway deployment logs
    cmds:
      - |
        if ! command -v railway &> /dev/null; then
          echo "Railway CLI not found. Install with: npm install -g @railway/cli"
          exit 1
        fi
      - railway logs

  install-railway-cli:
    desc: Install Railway CLI
    cmds:
      - npm install -g @railway/cli
      - echo "Railway CLI installed. Run 'railway login' to authenticate."
