version: '3'

vars:
  POCKETBASE_VERSION: 0.23.4
  POCKETBASE_DIR: '{{.ROOT_DIR}}'
  POCKETBASE_BIN: '{{.POCKETBASE_DIR}}/pocketbase'

tasks:
  install-pocketbase:
    desc: Download and install PocketBase for the current platform
    status:
      - test -f {{.POCKETBASE_BIN}}
    cmds:
      - echo "Installing PocketBase v{{.POCKETBASE_VERSION}}..."
      - |
        OS="{{OS}}"
        ARCH="{{ARCH}}"

        # Map OS names
        case "$OS" in
          darwin) OS_NAME="darwin" ;;
          linux) OS_NAME="linux" ;;
          windows) OS_NAME="windows" ;;
          *) echo "Unsupported OS: $OS"; exit 1 ;;
        esac

        # Map architecture names
        case "$ARCH" in
          amd64|x86_64) ARCH_NAME="amd64" ;;
          arm64|aarch64) ARCH_NAME="arm64" ;;
          *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
        esac

        DOWNLOAD_URL="https://github.com/pocketbase/pocketbase/releases/download/v{{.POCKETBASE_VERSION}}/pocketbase_{{.POCKETBASE_VERSION}}_${OS_NAME}_${ARCH_NAME}.zip"

        echo "Downloading from: $DOWNLOAD_URL"
        curl -L -o /tmp/pocketbase.zip "$DOWNLOAD_URL"

        echo "Extracting PocketBase..."
        unzip -q -o /tmp/pocketbase.zip -d {{.POCKETBASE_DIR}}

        chmod +x {{.POCKETBASE_BIN}}
        rm /tmp/pocketbase.zip

        echo "PocketBase installed successfully!"
        {{.POCKETBASE_BIN}} --version

  test:
    desc: Run all tests (unit and integration)
    deps: [install-pocketbase]
    cmds:
      - PATH={{.POCKETBASE_DIR}}:$PATH uv run pytest

  test-unit:
    desc: Run unit tests only
    cmds:
      - uv run pytest -m unit

  test-integration:
    desc: Run integration tests (requires PocketBase)
    deps: [install-pocketbase]
    cmds:
      - PATH={{.POCKETBASE_DIR}}:$PATH uv run pytest -m integration

  lint:
    desc: Run linting checks
    cmds:
      - uv run ruff check

  format:
    desc: Format code
    cmds:
      - uv run ruff format

  dev:
    desc: Run PocketBase and FastAPI for local development
    deps: [install-pocketbase]
    cmds:
      - defer: { task: stop-dev }
      - |
        echo "Starting PocketBase on http://127.0.0.1:8090..."
        {{.POCKETBASE_BIN}} serve > pocketbase.log 2>&1 &
        echo $! > .pocketbase.pid

        i=0; while [ $i -lt 10 ]; do
          curl -s http://127.0.0.1:8090/api/health > /dev/null 2>&1 && break
          sleep 1; i=$((i + 1))
        done
        echo "PocketBase is ready!"

        {{.POCKETBASE_BIN}} superuser upsert admin@test.local testpassword123 > /dev/null 2>&1 || true

        echo ""
        echo "Development environment ready!"
        echo "  PocketBase: http://127.0.0.1:8090"
        echo "  FastAPI:    http://0.0.0.0:8001"
        echo "  WAHA:       http://localhost:3000 (start with: docker-compose up -d waha)"
        echo ""
      - uv run uvicorn src.main:app --host 0.0.0.0 --port 8001

  stop-dev:
    desc: Stop all development services
    cmds:
      - |
        if [ -f .pocketbase.pid ]; then
          kill $(cat .pocketbase.pid) 2>/dev/null || true
          rm .pocketbase.pid
          echo "PocketBase stopped"
        fi
        if [ -f .fastapi.pid ]; then
          kill $(cat .fastapi.pid) 2>/dev/null || true
          rm .fastapi.pid
          echo "FastAPI stopped"
        fi
        echo "All services stopped"

  down:
    desc: Tear down all development services and clean up
    cmds:
      - |
        echo "Stopping all services..."

        # Stop services using PID files
        if [ -f .pocketbase.pid ]; then
          kill $(cat .pocketbase.pid) 2>/dev/null || true
          rm .pocketbase.pid
          echo "✓ PocketBase stopped (via PID file)"
        fi

        if [ -f .fastapi.pid ]; then
          kill $(cat .fastapi.pid) 2>/dev/null || true
          rm .fastapi.pid
          echo "✓ FastAPI stopped (via PID file)"
        fi

        # Kill any remaining processes by port
        POCKETBASE_PID=$(lsof -ti :8090) || true
        if [ -n "$POCKETBASE_PID" ]; then
          kill $POCKETBASE_PID 2>/dev/null || true
          echo "✓ PocketBase stopped (port 8090)"
        fi

        FASTAPI_PID=$(lsof -ti :8001) || true
        if [ -n "$FASTAPI_PID" ]; then
          kill $FASTAPI_PID 2>/dev/null || true
          echo "✓ FastAPI stopped (port 8001)"
        fi

        # Clean up log files
        if [ -f pocketbase.log ]; then
          rm pocketbase.log
          echo "✓ Removed pocketbase.log"
        fi

        if [ -f fastapi.log ]; then
          rm fastapi.log
          echo "✓ Removed fastapi.log"
        fi

        echo ""
        echo "All services stopped and cleaned up!"

  clean:
    desc: Remove PocketBase binary and data
    cmds:
      - rm -f {{.POCKETBASE_BIN}}
      - rm -rf pb_data
      - rm -rf pb_migrations

  deploy:
    desc: Deploy to Railway (requires Railway CLI)
    cmds:
      - |
        if ! command -v railway &> /dev/null; then
          echo "Railway CLI not found. Install with: npm install -g @railway/cli"
          exit 1
        fi
      - echo "Deploying to Railway..."
      - railway up

  deploy-status:
    desc: Check Railway deployment status
    cmds:
      - |
        if ! command -v railway &> /dev/null; then
          echo "Railway CLI not found. Install with: npm install -g @railway/cli"
          exit 1
        fi
      - railway status

  deploy-logs:
    desc: View Railway deployment logs
    cmds:
      - |
        if ! command -v railway &> /dev/null; then
          echo "Railway CLI not found. Install with: npm install -g @railway/cli"
          exit 1
        fi
      - railway logs

  install-railway-cli:
    desc: Install Railway CLI
    cmds:
      - npm install -g @railway/cli
      - echo "Railway CLI installed. Run 'railway login' to authenticate."
