version: '3'

tasks:
  test:
    desc: Run all tests (unit and integration)
    cmds:
      - uv run pytest

  test-unit:
    desc: Run unit tests only
    cmds:
      - uv run pytest -m unit

  test-integration:
    desc: Run integration tests
    cmds:
      - uv run pytest -m integration

  lint:
    desc: Run linting checks
    cmds:
      - uv run ruff check

  format:
    desc: Format code
    cmds:
      - uv run ruff format

  dev:
    desc: Run FastAPI for local development
    cmds:
      - |
        echo "Starting development environment..."
        echo "Starting FastAPI on http://0.0.0.0:8001..."
        NO_COLOR=1 uv run uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload

  clean:
    desc: Remove data directory
    cmds:
      - rm -rf data
