"""Activation key service for group activation flow."""

import secrets


# Common, memorable words for activation keys
# Mix of animals, colors, objects, nature words - all lowercase, no confusion
WORD_LIST = [
    # Animals
    "tiger",
    "eagle",
    "dolphin",
    "panda",
    "falcon",
    "wolf",
    "bear",
    "lion",
    "hawk",
    "shark",
    "whale",
    "fox",
    "deer",
    "owl",
    "swan",
    "raven",
    "otter",
    "seal",
    "moose",
    "elk",
    "bison",
    "crane",
    "heron",
    "finch",
    "robin",
    "sparrow",
    "salmon",
    "trout",
    "bass",
    "pike",
    "crab",
    "clam",
    # Colors
    "red",
    "blue",
    "green",
    "gold",
    "silver",
    "bronze",
    "amber",
    "coral",
    "jade",
    "ruby",
    "pearl",
    "ivory",
    "ebony",
    "crimson",
    "azure",
    "indigo",
    "violet",
    "scarlet",
    "copper",
    "brass",
    "cobalt",
    "cyan",
    "magenta",
    "teal",
    # Nature
    "mountain",
    "river",
    "forest",
    "ocean",
    "meadow",
    "canyon",
    "valley",
    "island",
    "desert",
    "glacier",
    "volcano",
    "waterfall",
    "prairie",
    "marsh",
    "reef",
    "cliff",
    "cave",
    "lake",
    "stream",
    "pond",
    "hill",
    "peak",
    "ridge",
    "shore",
    "beach",
    "dune",
    "grove",
    "field",
    "garden",
    "orchard",
    "jungle",
    "swamp",
    # Objects
    "hammer",
    "anchor",
    "compass",
    "lantern",
    "candle",
    "mirror",
    "crown",
    "shield",
    "sword",
    "arrow",
    "bridge",
    "tower",
    "castle",
    "cabin",
    "wagon",
    "vessel",
    "barrel",
    "basket",
    "ladder",
    "window",
    "door",
    "gate",
    "fence",
    "wheel",
    "chain",
    "rope",
    "bell",
    "drum",
    "horn",
    "flute",
    "harp",
    "piano",
    # Food
    "apple",
    "orange",
    "lemon",
    "cherry",
    "grape",
    "peach",
    "mango",
    "melon",
    "berry",
    "plum",
    "olive",
    "walnut",
    "almond",
    "hazel",
    "maple",
    "honey",
    "pepper",
    "ginger",
    "basil",
    "sage",
    "mint",
    "thyme",
    "clover",
    "wheat",
    # Weather/Sky
    "storm",
    "thunder",
    "lightning",
    "rainbow",
    "sunset",
    "sunrise",
    "dawn",
    "dusk",
    "cloud",
    "rain",
    "snow",
    "frost",
    "mist",
    "fog",
    "wind",
    "breeze",
    "comet",
    "meteor",
    "star",
    "moon",
    "sun",
    "nova",
    "orbit",
    "eclipse",
    # Materials
    "stone",
    "crystal",
    "diamond",
    "marble",
    "granite",
    "quartz",
    "flint",
    "slate",
    "iron",
    "steel",
    "bronze",
    "tin",
    "zinc",
    "chrome",
    "nickel",
    "platinum",
    # Actions/Concepts
    "swift",
    "bold",
    "brave",
    "calm",
    "bright",
    "clear",
    "fresh",
    "keen",
    "noble",
    "royal",
    "grand",
    "prime",
    "chief",
    "major",
    "sonic",
    "rapid",
]


def generate_activation_key() -> str:
    """Generate a 3-word activation key.

    Returns:
        A hyphen-separated key like "tiger-mountain-gold"
    """
    words = [secrets.choice(WORD_LIST) for _ in range(3)]
    return "-".join(words)


def check_activation_message(text: str, activation_key: str) -> bool:
    """Check if a message exactly matches the activation key.

    Args:
        text: The message text to check
        activation_key: The current activation key to match against

    Returns:
        True if the message matches the activation key (case-insensitive)
    """
    if not text or not activation_key:
        return False

    return text.strip().lower() == activation_key.strip().lower()
