"""initial

Revision ID: 5b6060d3e36c
Revises:
Create Date: 2026-03-05 13:01:24.039279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # type: ignore[import-untyped]


# revision identifiers, used by Alembic.
revision: str = "5b6060d3e36c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("whatsapp_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "role", sa.Enum("ADMIN", "MEMBER", name="memberrole"), nullable=False
        ),
        sa.Column(
            "status", sa.Enum("PENDING", "ACTIVE", name="memberstatus"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("member", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_member_whatsapp_id"), ["whatsapp_id"], unique=True
        )

    op.create_table(
        "messagejob",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("group_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "DONE", "FAILED", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messagejob", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_messagejob_sender_id"), ["sender_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_messagejob_status"), ["status"], unique=False
        )

    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("assignee_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CLAIMED", "VERIFIED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column(
            "verification_mode",
            sa.Enum("NONE", "PEER", "PARTNER", name="verificationmode"),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("SHARED", "PERSONAL", name="taskvisibility"),
            nullable=False,
        ),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column("recurrence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("next_deadline", sa.DateTime(), nullable=True),
        sa.Column("deletion_requested_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deletion_requested_by"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["member.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_assignee_id"), ["assignee_id"], unique=False
        )

    op.create_table(
        "completionhistory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("completed_by_id", sa.Integer(), nullable=False),
        sa.Column("verified_by_id", sa.Integer(), nullable=True),
        sa.Column("feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["completed_by_id"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"],
            ["member.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("completionhistory", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_completionhistory_task_id"), ["task_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("completionhistory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_completionhistory_task_id"))

    op.drop_table("completionhistory")
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_assignee_id"))

    op.drop_table("task")
    with op.batch_alter_table("messagejob", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messagejob_status"))
        batch_op.drop_index(batch_op.f("ix_messagejob_sender_id"))

    op.drop_table("messagejob")
    with op.batch_alter_table("member", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_member_whatsapp_id"))

    op.drop_table("member")
    # ### end Alembic commands ###
